# Generated by Django 4.2 on 2024-05-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_seat_seat_class_seat_status_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='status',
            new_name='is_reserved',
        ),
    ]
