# Generated by Django 4.2 on 2024-05-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('arrived_time', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.stationmodel')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.trainmodel')),
            ],
        ),
    ]
