# Generated by Django 4.2 on 2024-05-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_stationmodel_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationmodel',
            old_name='capacity',
            new_name='default_capacity',
        ),
    ]
