# Generated by Django 4.2 on 2024-05-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_rename_capacity_stationmodel_default_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationmodel',
            old_name='default_capacity',
            new_name='capacity',
        ),
    ]
